<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include_once("$curr_dir/lib.php");

	handle_maintenance();

	// drop-downs config
	$lookups = array(
		'jpd_de' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Waran' => array(
				'parent_table' => 'waran',
				'parent_pk_field' => 'id',
				'parent_caption' => '`waran`.`sumber_waran`',
				'parent_from' => '`waran` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_jpd',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_jpd`.`skop_jpd`',
				'parent_from' => '`skop_jpd` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pams_DE' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Waran' => array(
				'parent_table' => 'waran',
				'parent_pk_field' => 'id',
				'parent_caption' => '`waran`.`sumber_waran`',
				'parent_from' => '`waran` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_pams',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_pams`.`skop_pams`',
				'parent_from' => '`skop_pams` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'JL' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_jpd',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_jpd`.`skop_jpd`',
				'parent_from' => '`skop_jpd` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'jpd_khas' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Waran' => array(
				'parent_table' => 'waran',
				'parent_pk_field' => 'id',
				'parent_caption' => '`waran`.`sumber_waran`',
				'parent_from' => '`waran` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `kelulusan`.`id`, `kelulusan`.`kelulusan_jawatankuasa` FROM `kelulusan` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => 'SELECT `daerah`.`id`, `daerah`.`nama_daerah` FROM `daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => 'SELECT `PARLIMEN`.`id`, `PARLIMEN`.`nama_parlimen` FROM `PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_jpd',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_jpd`.`skop_jpd`',
				'parent_from' => '`skop_jpd` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `status_pelaksanaan`.`id`, `status_pelaksanaan`.`status_laksana` FROM `status_pelaksanaan` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pams_khas' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Waran' => array(
				'parent_table' => 'waran',
				'parent_pk_field' => 'id',
				'parent_caption' => '`waran`.`sumber_waran`',
				'parent_from' => '`waran` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_pams',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_pams`.`skop_pams`',
				'parent_from' => '`skop_pams` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'jpd_noc' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pams_noc' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'balb' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Waran' => array(
				'parent_table' => 'waran',
				'parent_pk_field' => 'id',
				'parent_caption' => '`waran`.`sumber_waran`',
				'parent_from' => '`waran` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'JALB' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'BELB' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Waran' => array(
				'parent_table' => 'waran',
				'parent_pk_field' => 'id',
				'parent_caption' => '`waran`.`sumber_waran`',
				'parent_from' => '`waran` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pprt' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'ekasih' => array(
				'parent_table' => 'ekasih',
				'parent_pk_field' => 'id',
				'parent_caption' => '`ekasih`.`status_ekasih`',
				'parent_from' => '`ekasih` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'ljk' => array(
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'dun' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'jenis_lampu' => array(
				'parent_table' => 'LJK_JENIS',
				'parent_pk_field' => 'id',
				'parent_caption' => '`LJK_JENIS`.`jenis_lampu`',
				'parent_from' => '`LJK_JENIS` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pemohon_jpd' => array(
			'tahun' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array('negeri' => 'negeri', 'Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_jpd',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_jpd`.`skop_jpd`',
				'parent_from' => '`skop_jpd` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pams_mohon' => array(
			'tahun' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array('Daerah' => 'daerah'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'skop' => array(
				'parent_table' => 'skop_pams',
				'parent_pk_field' => 'id',
				'parent_caption' => '`skop_pams`.`skop_pams`',
				'parent_from' => '`skop_pams` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pemohon_pprt' => array(
			'tahun' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'negeri' => array(
		),
		'daerah' => array(
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'Dun' => array(
			'daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'PARLIMEN' => array(
			'daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array('negeri' => 'negeri'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'kelulusan' => array(
		),
		'status_pelaksanaan' => array(
		),
		'status_kelulusan_jpd' => array(
			'pemohon' => array(
				'parent_table' => 'pemohon_jpd',
				'parent_pk_field' => 'ID',
				'parent_caption' => 'IF(CHAR_LENGTH(`pemohon_jpd`.`Nama_Projek`) || CHAR_LENGTH(`pemohon_jpd`.`anggaran_kos`), CONCAT_WS(\'\', `pemohon_jpd`.`Nama_Projek`, \'- RM\', `pemohon_jpd`.`anggaran_kos`), \'\')',
				'parent_from' => '`pemohon_jpd` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pemohon_jpd`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pemohon_jpd`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pemohon_jpd`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pemohon_jpd`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pemohon_jpd`.`DUN` LEFT JOIN `skop_jpd` as skop_jpd1 ON `skop_jpd1`.`id`=`pemohon_jpd`.`skop` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `pemohon_jpd`.`ID`, `pemohon_jpd`.`Nama_Projek` FROM `pemohon_jpd` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pemohon_jpd`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pemohon_jpd`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pemohon_jpd`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pemohon_jpd`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pemohon_jpd`.`DUN` WHERE pemohon_jpd.status_permohonan = \'baru\' ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'status_kelulusan_pams' => array(
			'pemohon' => array(
				'parent_table' => 'pams_mohon',
				'parent_pk_field' => 'ID',
				'parent_caption' => 'IF(CHAR_LENGTH(`pams_mohon`.`Nama_Projek`) || CHAR_LENGTH(`pams_mohon`.`anggaran_kos`), CONCAT_WS(\'\', `pams_mohon`.`Nama_Projek`, \'- RM\', `pams_mohon`.`anggaran_kos`), \'\')',
				'parent_from' => '`pams_mohon` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pams_mohon`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pams_mohon`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pams_mohon`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pams_mohon`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pams_mohon`.`DUN` LEFT JOIN `skop_pams` as skop_pams1 ON `skop_pams1`.`id`=`pams_mohon`.`skop` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `pams_mohon`.`ID`, `pams_mohon`.`Nama_Projek` FROM `pams_mohon` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pams_mohon`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pams_mohon`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pams_mohon`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pams_mohon`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pams_mohon`.`DUN` WHERE pams_mohon.status_permohonan = \'baru\' ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'status_kelulusan_pprt' => array(
			'pemohon' => array(
				'parent_table' => 'pemohon_pprt',
				'parent_pk_field' => 'ID',
				'parent_caption' => 'IF(CHAR_LENGTH(`pemohon_pprt`.`Nama_pemohon`) || CHAR_LENGTH(`pemohon_pprt`.`anggaran_kos`), CONCAT_WS(\'\', `pemohon_pprt`.`Nama_pemohon`, \'- RM\', `pemohon_pprt`.`anggaran_kos`), \'\')',
				'parent_from' => '`pemohon_pprt` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pemohon_pprt`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pemohon_pprt`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pemohon_pprt`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pemohon_pprt`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pemohon_pprt`.`DUN` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `pemohon_pprt`.`ID`, IF(CHAR_LENGTH(`pemohon_pprt`.`Nama_pemohon`) || CHAR_LENGTH(`pemohon_pprt`.`anggaran_kos`), CONCAT_WS(\'\', `pemohon_pprt`.`Nama_pemohon`, \'- RM\', `pemohon_pprt`.`anggaran_kos`), \'\') FROM `pemohon_pprt` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pemohon_pprt`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pemohon_pprt`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pemohon_pprt`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pemohon_pprt`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pemohon_pprt`.`DUN` WHERE pemohon_pprt.status_permohonan = \'baru\' ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'tahun' => array(
		),
		'penyelia_projek' => array(
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'agensi_pelaksana' => array(
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'agensi_bayar' => array(
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'waran' => array(
		),
		'jpd_de_REKOD' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'pams_DE_REKOD' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'jpd_test' => array(
			'tahun_laksana' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Kelulusan' => array(
				'parent_table' => 'kelulusan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`kelulusan`.`kelulusan_jawatankuasa`',
				'parent_from' => '`kelulusan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Daerah' => array(
				'parent_table' => 'daerah',
				'parent_pk_field' => 'id',
				'parent_caption' => '`daerah`.`nama_daerah`',
				'parent_from' => '`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`daerah`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Parlimen' => array(
				'parent_table' => 'PARLIMEN',
				'parent_pk_field' => 'id',
				'parent_caption' => '`PARLIMEN`.`nama_parlimen`',
				'parent_from' => '`PARLIMEN` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`PARLIMEN`.`daerah` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`PARLIMEN`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'DUN' => array(
				'parent_table' => 'Dun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Dun`.`nama_dun`',
				'parent_from' => '`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'AgensiPelaksana' => array(
				'parent_table' => 'agensi_pelaksana',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_pelaksana`.`pelaksana`',
				'parent_from' => '`agensi_pelaksana` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_pelaksana`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agensi_pembayar' => array(
				'parent_table' => 'agensi_bayar',
				'parent_pk_field' => 'id',
				'parent_caption' => '`agensi_bayar`.`agensi`',
				'parent_from' => '`agensi_bayar` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`agensi_bayar`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'penyelia_projek' => array(
				'parent_table' => 'penyelia_projek',
				'parent_pk_field' => 'id',
				'parent_caption' => '`penyelia_projek`.`nama_penyelia`',
				'parent_from' => '`penyelia_projek` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`penyelia_projek`.`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Status' => array(
				'parent_table' => 'status_pelaksanaan',
				'parent_pk_field' => 'id',
				'parent_caption' => '`status_pelaksanaan`.`status_laksana`',
				'parent_from' => '`status_pelaksanaan` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'skop_jpd' => array(
		),
		'skop_pams' => array(
		),
		'Syarikat' => array(
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'Tahun_lantik' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'blacklist' => array(
				'parent_table' => 'BLACKLIST',
				'parent_pk_field' => 'ID',
				'parent_caption' => 'IF(CHAR_LENGTH(`BLACKLIST`.`disenaraihitamkan`) || CHAR_LENGTH(`BLACKLIST`.`sebab`), CONCAT_WS(\'\', `BLACKLIST`.`disenaraihitamkan`, \'-\', `BLACKLIST`.`sebab`), \'\')',
				'parent_from' => '`BLACKLIST` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'Syarikat_baru' => array(
			'Tahun_daftar' => array(
				'parent_table' => 'tahun',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tahun`.`tahun`',
				'parent_from' => '`tahun` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'negeri' => array(
				'parent_table' => 'negeri',
				'parent_pk_field' => 'id',
				'parent_caption' => '`negeri`.`nama_negeri`',
				'parent_from' => '`negeri` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'ekasih' => array(
		),
		'BLACKLIST' => array(
		),
		'LJK_JENIS' => array(
		),
		'Laporan_N9' => array(
		),
		'Laporan_MLK' => array(
		),
	);

	// XSS prevention
	$xss = new CI_Input(datalist_db_encoding);

	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(from_utf8($_REQUEST['id']));
	$selected_text = from_utf8($_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8($_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm['access'] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = [];

	// search term provided?
	if($search_term) {
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])) {
		foreach($field['filterers'] as $filterer => $filterer_parent) {
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get) {
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']) {
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id) {
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)) {
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']) {
		$qm = []; $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)) {
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)) {
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where) {
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		} elseif($custom_where) {
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		} else {
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = [];
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])) {
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		} else {
			$count_query = '';
		}
	} else {
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id) {
		$combo->SelectedData = $search_id;
	} elseif($selected_text) {
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2) {
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions) {
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		} else {
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>">
			<?php
		}
	} else {
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)) {
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = [];

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text) {
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text)));
		} else {
			/*
			 * in case we have a search term, show matches starting with it first,
			 * followed by those containing it.
			 * build a UNION query for that purpose
			 */
			if($search_term) {
				$query2 = $combo->Query;
				$query1 = str_replace(" like '%{$search_term}%'", " like '{$search_term}%'", $query2);
				$combo->Query = "({$query1}) UNION ({$query2})";
			}

			$eo = ['silentErrors' => true];

			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)) {
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']) {
					$prepared_data[] = array('id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>"));
				}

				$prepared_data[] = array('id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1])));
			}
		}

		if(empty($prepared_data)) { $prepared_data[] = array('id' => '', 'text' => to_utf8($Translation['No matches found!'])); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

