<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/Dun.php");
	include_once("{$currDir}/Dun_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('Dun');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Dun';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Dun`.`id`" => "id",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "daerah",
		"`Dun`.`nama_dun`" => "nama_dun",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "parlimen",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Dun`.`id`',
		2 => '`daerah1`.`nama_daerah`',
		3 => 3,
		4 => '`PARLIMEN1`.`nama_parlimen`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Dun`.`id`" => "id",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "daerah",
		"`Dun`.`nama_dun`" => "nama_dun",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "parlimen",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Dun`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"`Dun`.`nama_dun`" => "Nama dun",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Dun`.`id`" => "id",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "daerah",
		"`Dun`.`nama_dun`" => "nama_dun",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "parlimen",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['daerah' => 'Daerah', 'parlimen' => 'Parlimen', ];

	$x->QueryFrom = "`Dun` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`Dun`.`daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`Dun`.`parlimen` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Dun_view.php';
	$x->RedirectAfterInsert = 'Dun_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Dun';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Dun`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Daerah', 'Nama dun', 'Parlimen', ];
	$x->ColFieldName = ['id', 'daerah', 'nama_dun', 'parlimen', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Dun_templateTV.html';
	$x->SelectedTemplate = 'templates/Dun_templateTVS.html';
	$x->TemplateDV = 'templates/Dun_templateDV.html';
	$x->TemplateDVP = 'templates/Dun_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Dun_init
	$render = true;
	if(function_exists('Dun_init')) {
		$args = [];
		$render = Dun_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Dun_header
	$headerCode = '';
	if(function_exists('Dun_header')) {
		$args = [];
		$headerCode = Dun_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Dun_footer
	$footerCode = '';
	if(function_exists('Dun_footer')) {
		$args = [];
		$footerCode = Dun_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
