<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/jpd_noc.php");
	include_once("{$currDir}/jpd_noc_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('jpd_noc');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'jpd_noc';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`jpd_noc`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "tahun_laksana",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`jpd_noc`.`NamaProjek`" => "NamaProjek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "AgensiPelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi Pembayar */" => "agensi_pembayar",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "penyelia_projek",
		"`jpd_noc`.`NamaKontraktor`" => "NamaKontraktor",
		"if(`jpd_noc`.`TarikhSST`,date_format(`jpd_noc`.`TarikhSST`,'%d/%m/%Y'),'')" => "TarikhSST",
		"if(`jpd_noc`.`TarikhSiapProjek`,date_format(`jpd_noc`.`TarikhSiapProjek`,'%d/%m/%Y'),'')" => "TarikhSiapProjek",
		"`jpd_noc`.`TarikhSiapSepenuhnya`" => "TarikhSiapSepenuhnya",
		"`jpd_noc`.`PanjangJalanM`" => "PanjangJalanM",
		"`jpd_noc`.`gambar_projek`" => "gambar_projek",
		"`jpd_noc`.`LebarM`" => "LebarM",
		"`jpd_noc`.`Latitud`" => "Latitud",
		"`jpd_noc`.`Longitud`" => "Longitud",
		"FORMAT(`jpd_noc`.`PeruntukanDiluluskan`, 2)" => "PeruntukanDiluluskan",
		"`jpd_noc`.`peruntukan_dipinda`" => "peruntukan_dipinda",
		"FORMAT(`jpd_noc`.`Kosprojek`, 2)" => "Kosprojek",
		"FORMAT(`jpd_noc`.`KKSVO`, 2)" => "KKSVO",
		"`jpd_noc`.`Perbelanjaan`" => "Perbelanjaan",
		"`jpd_noc`.`penjimatan`" => "penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"`jpd_noc`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`jpd_noc`.`sumber_permohonan`" => "sumber_permohonan",
		"`jpd_noc`.`catatan`" => "catatan",
		"`jpd_noc`.`inden`" => "inden",
		"`jpd_noc`.`Baucer`" => "Baucer",
		"`jpd_noc`.`gambar_projek_1`" => "gambar_projek_1",
		"`jpd_noc`.`gambar_projek_2`" => "gambar_projek_2",
		"`jpd_noc`.`updated`" => "updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`jpd_noc`.`ID`',
		2 => '`tahun1`.`tahun`',
		3 => '`kelulusan1`.`kelulusan_jawatankuasa`',
		4 => 4,
		5 => '`negeri1`.`nama_negeri`',
		6 => '`daerah1`.`nama_daerah`',
		7 => '`PARLIMEN1`.`nama_parlimen`',
		8 => '`Dun1`.`nama_dun`',
		9 => '`agensi_pelaksana1`.`pelaksana`',
		10 => '`agensi_bayar1`.`agensi`',
		11 => '`penyelia_projek1`.`nama_penyelia`',
		12 => 12,
		13 => '`jpd_noc`.`TarikhSST`',
		14 => '`jpd_noc`.`TarikhSiapProjek`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => '`jpd_noc`.`PeruntukanDiluluskan`',
		22 => '`jpd_noc`.`peruntukan_dipinda`',
		23 => '`jpd_noc`.`Kosprojek`',
		24 => '`jpd_noc`.`KKSVO`',
		25 => '`jpd_noc`.`Perbelanjaan`',
		26 => '`jpd_noc`.`penjimatan`',
		27 => '`status_pelaksanaan1`.`status_laksana`',
		28 => 28,
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => 35,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`jpd_noc`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "tahun_laksana",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`jpd_noc`.`NamaProjek`" => "NamaProjek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "AgensiPelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi Pembayar */" => "agensi_pembayar",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "penyelia_projek",
		"`jpd_noc`.`NamaKontraktor`" => "NamaKontraktor",
		"if(`jpd_noc`.`TarikhSST`,date_format(`jpd_noc`.`TarikhSST`,'%d/%m/%Y'),'')" => "TarikhSST",
		"if(`jpd_noc`.`TarikhSiapProjek`,date_format(`jpd_noc`.`TarikhSiapProjek`,'%d/%m/%Y'),'')" => "TarikhSiapProjek",
		"`jpd_noc`.`TarikhSiapSepenuhnya`" => "TarikhSiapSepenuhnya",
		"`jpd_noc`.`PanjangJalanM`" => "PanjangJalanM",
		"`jpd_noc`.`gambar_projek`" => "gambar_projek",
		"`jpd_noc`.`LebarM`" => "LebarM",
		"`jpd_noc`.`Latitud`" => "Latitud",
		"`jpd_noc`.`Longitud`" => "Longitud",
		"FORMAT(`jpd_noc`.`PeruntukanDiluluskan`, 2)" => "PeruntukanDiluluskan",
		"`jpd_noc`.`peruntukan_dipinda`" => "peruntukan_dipinda",
		"FORMAT(`jpd_noc`.`Kosprojek`, 2)" => "Kosprojek",
		"FORMAT(`jpd_noc`.`KKSVO`, 2)" => "KKSVO",
		"`jpd_noc`.`Perbelanjaan`" => "Perbelanjaan",
		"`jpd_noc`.`penjimatan`" => "penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"`jpd_noc`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`jpd_noc`.`sumber_permohonan`" => "sumber_permohonan",
		"`jpd_noc`.`catatan`" => "catatan",
		"`jpd_noc`.`inden`" => "inden",
		"`jpd_noc`.`Baucer`" => "Baucer",
		"`jpd_noc`.`gambar_projek_1`" => "gambar_projek_1",
		"`jpd_noc`.`gambar_projek_2`" => "gambar_projek_2",
		"`jpd_noc`.`updated`" => "updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`jpd_noc`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "Tahun laksana",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`jpd_noc`.`NamaProjek`" => "Nama Projek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "Negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "Agensi Pelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi Pembayar */" => "Agensi Pembayar",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "Penyelia projek",
		"`jpd_noc`.`NamaKontraktor`" => "Nama Kontraktor",
		"`jpd_noc`.`TarikhSST`" => "Tarikh SST",
		"`jpd_noc`.`TarikhSiapProjek`" => "Tarikh Siap Projek",
		"`jpd_noc`.`TarikhSiapSepenuhnya`" => "Tarikh Siap Sepenuhnya",
		"`jpd_noc`.`PanjangJalanM`" => "Panjang Jalan (M)",
		"`jpd_noc`.`LebarM`" => "Lebar (M)",
		"`jpd_noc`.`Latitud`" => "Latitud",
		"`jpd_noc`.`Longitud`" => "Longitud",
		"`jpd_noc`.`PeruntukanDiluluskan`" => "Peruntukan Diluluskan",
		"`jpd_noc`.`peruntukan_dipinda`" => "Peruntukan Dipinda",
		"`jpd_noc`.`Kosprojek`" => "Kos projek",
		"`jpd_noc`.`KKSVO`" => "KKSVO",
		"`jpd_noc`.`Perbelanjaan`" => "Perbelanjaan",
		"`jpd_noc`.`penjimatan`" => "penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"`jpd_noc`.`PenerimaManfaat`" => "Penerima Manfaat",
		"`jpd_noc`.`sumber_permohonan`" => "Sumber Permohonan",
		"`jpd_noc`.`catatan`" => "Catatan",
		"`jpd_noc`.`inden`" => "Inden Kerja",
		"`jpd_noc`.`Baucer`" => "Baucer Bayaran",
		"`jpd_noc`.`updated`" => "Dikemaskini Oleh",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`jpd_noc`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "tahun_laksana",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`jpd_noc`.`NamaProjek`" => "NamaProjek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "AgensiPelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi Pembayar */" => "agensi_pembayar",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "penyelia_projek",
		"`jpd_noc`.`NamaKontraktor`" => "NamaKontraktor",
		"if(`jpd_noc`.`TarikhSST`,date_format(`jpd_noc`.`TarikhSST`,'%d/%m/%Y'),'')" => "TarikhSST",
		"if(`jpd_noc`.`TarikhSiapProjek`,date_format(`jpd_noc`.`TarikhSiapProjek`,'%d/%m/%Y'),'')" => "TarikhSiapProjek",
		"`jpd_noc`.`TarikhSiapSepenuhnya`" => "TarikhSiapSepenuhnya",
		"`jpd_noc`.`PanjangJalanM`" => "PanjangJalanM",
		"`jpd_noc`.`LebarM`" => "LebarM",
		"`jpd_noc`.`Latitud`" => "Latitud",
		"`jpd_noc`.`Longitud`" => "Longitud",
		"FORMAT(`jpd_noc`.`PeruntukanDiluluskan`, 2)" => "PeruntukanDiluluskan",
		"`jpd_noc`.`peruntukan_dipinda`" => "peruntukan_dipinda",
		"FORMAT(`jpd_noc`.`Kosprojek`, 2)" => "Kosprojek",
		"FORMAT(`jpd_noc`.`KKSVO`, 2)" => "KKSVO",
		"`jpd_noc`.`Perbelanjaan`" => "Perbelanjaan",
		"`jpd_noc`.`penjimatan`" => "penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"`jpd_noc`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`jpd_noc`.`sumber_permohonan`" => "sumber_permohonan",
		"`jpd_noc`.`catatan`" => "catatan",
		"`jpd_noc`.`inden`" => "inden",
		"`jpd_noc`.`Baucer`" => "Baucer",
		"`jpd_noc`.`updated`" => "updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['tahun_laksana' => 'Tahun laksana', 'Kelulusan' => 'Kelulusan', 'negeri' => 'Negeri', 'Daerah' => 'Daerah', 'Parlimen' => 'Parlimen', 'DUN' => 'DUN', 'AgensiPelaksana' => 'Agensi Pelaksana', 'agensi_pembayar' => 'Agensi Pembayar', 'penyelia_projek' => 'Penyelia projek', 'Status' => 'Status', ];

	$x->QueryFrom = "`jpd_noc` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`jpd_noc`.`tahun_laksana` LEFT JOIN `kelulusan` as kelulusan1 ON `kelulusan1`.`id`=`jpd_noc`.`Kelulusan` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`jpd_noc`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`jpd_noc`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`jpd_noc`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`jpd_noc`.`DUN` LEFT JOIN `agensi_pelaksana` as agensi_pelaksana1 ON `agensi_pelaksana1`.`id`=`jpd_noc`.`AgensiPelaksana` LEFT JOIN `agensi_bayar` as agensi_bayar1 ON `agensi_bayar1`.`id`=`jpd_noc`.`agensi_pembayar` LEFT JOIN `penyelia_projek` as penyelia_projek1 ON `penyelia_projek1`.`id`=`jpd_noc`.`penyelia_projek` LEFT JOIN `status_pelaksanaan` as status_pelaksanaan1 ON `status_pelaksanaan1`.`id`=`jpd_noc`.`Status` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 5;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'jpd_noc_view.php';
	$x->RedirectAfterInsert = 'jpd_noc_view.php?SelectedID=#ID#';
	$x->TableTitle = 'JPD NOC';
	$x->TableIcon = 'resources/table_icons/car.png';
	$x->PrimaryKey = '`jpd_noc`.`ID`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tahun laksana', 'Kelulusan', 'Nama Projek', 'Negeri', 'Daerah', 'Parlimen', 'DUN', 'Penyelia projek', 'Nama Kontraktor', 'Tarikh SST', 'Tarikh Siap Sepenuhnya', 'Panjang Jalan (M)', 'Gambar ', 'Lebar (M)', 'Peruntukan Diluluskan', 'Kos projek', 'KKSVO', 'Perbelanjaan', 'penjimatan', 'Status', 'Penerima Manfaat', 'Sumber Permohonan', 'Catatan', 'Inden Kerja', 'Baucer Bayaran', 'Gambar  ', 'Gambar   ', 'Dikemaskini Oleh', ];
	$x->ColFieldName = ['tahun_laksana', 'Kelulusan', 'NamaProjek', 'negeri', 'Daerah', 'Parlimen', 'DUN', 'penyelia_projek', 'NamaKontraktor', 'TarikhSST', 'TarikhSiapSepenuhnya', 'PanjangJalanM', 'gambar_projek', 'LebarM', 'PeruntukanDiluluskan', 'Kosprojek', 'KKSVO', 'Perbelanjaan', 'penjimatan', 'Status', 'PenerimaManfaat', 'sumber_permohonan', 'catatan', 'inden', 'Baucer', 'gambar_projek_1', 'gambar_projek_2', 'updated', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 15, 16, 17, 18, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/jpd_noc_templateTV.html';
	$x->SelectedTemplate = 'templates/jpd_noc_templateTVS.html';
	$x->TemplateDV = 'templates/jpd_noc_templateDV.html';
	$x->TemplateDVP = 'templates/jpd_noc_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: jpd_noc_init
	$render = true;
	if(function_exists('jpd_noc_init')) {
		$args = [];
		$render = jpd_noc_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: jpd_noc_header
	$headerCode = '';
	if(function_exists('jpd_noc_header')) {
		$args = [];
		$headerCode = jpd_noc_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: jpd_noc_footer
	$footerCode = '';
	if(function_exists('jpd_noc_footer')) {
		$args = [];
		$footerCode = jpd_noc_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
