<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/Kew_n9.php");
	include_once("{$currDir}/Kew_n9_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('Kew_n9');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Kew_n9';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Kew_n9`.`ID`" => "ID",
		"`Kew_n9`.`program`" => "program",
		"`Kew_n9`.`bil_projek`" => "bil_projek",
		"FORMAT(`Kew_n9`.`peruntukan`, 2)" => "peruntukan",
		"FORMAT(`Kew_n9`.`belanja`, 2)" => "belanja",
		"FORMAT(`Kew_n9`.`jimat`, 2)" => "jimat",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Kew_n9`.`ID`',
		2 => 2,
		3 => '`Kew_n9`.`bil_projek`',
		4 => '`Kew_n9`.`peruntukan`',
		5 => '`Kew_n9`.`belanja`',
		6 => '`Kew_n9`.`jimat`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Kew_n9`.`ID`" => "ID",
		"`Kew_n9`.`program`" => "program",
		"`Kew_n9`.`bil_projek`" => "bil_projek",
		"FORMAT(`Kew_n9`.`peruntukan`, 2)" => "peruntukan",
		"FORMAT(`Kew_n9`.`belanja`, 2)" => "belanja",
		"FORMAT(`Kew_n9`.`jimat`, 2)" => "jimat",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Kew_n9`.`ID`" => "ID",
		"`Kew_n9`.`program`" => "Program",
		"`Kew_n9`.`bil_projek`" => "BILANGAN PROJEK",
		"`Kew_n9`.`peruntukan`" => "PERUNTUKAN (RM)",
		"`Kew_n9`.`belanja`" => "BELANJA",
		"`Kew_n9`.`jimat`" => "PENJIMATAN",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Kew_n9`.`ID`" => "ID",
		"`Kew_n9`.`program`" => "program",
		"`Kew_n9`.`bil_projek`" => "bil_projek",
		"FORMAT(`Kew_n9`.`peruntukan`, 2)" => "peruntukan",
		"FORMAT(`Kew_n9`.`belanja`, 2)" => "belanja",
		"FORMAT(`Kew_n9`.`jimat`, 2)" => "jimat",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Kew_n9` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Kew_n9_view.php';
	$x->RedirectAfterInsert = 'Kew_n9_view.php?SelectedID=#ID#';
	$x->TableTitle = 'KEWANGAN NEGERI SEMBILAN';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Kew_n9`.`ID`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Program', 'BILANGAN PROJEK', 'PERUNTUKAN (RM)', 'BELANJA', 'PENJIMATAN', ];
	$x->ColFieldName = ['program', 'bil_projek', 'peruntukan', 'belanja', 'jimat', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Kew_n9_templateTV.html';
	$x->SelectedTemplate = 'templates/Kew_n9_templateTVS.html';
	$x->TemplateDV = 'templates/Kew_n9_templateDV.html';
	$x->TemplateDVP = 'templates/Kew_n9_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Kew_n9_init
	$render = true;
	if(function_exists('Kew_n9_init')) {
		$args = [];
		$render = Kew_n9_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])) {
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `Kew_n9`.`ID` in ('.substr($QueryWhere, 0, -1).')';
			} else { // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		} else {
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "SELECT SUM(`Kew_n9`.`bil_projek`), FORMAT(SUM(`Kew_n9`.`peruntukan`), 2) FROM {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success sum">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<th class="text-center sum">&sum;</th>';
			$sumRow .= '<td class="Kew_n9-program sum"></td>';
			$sumRow .= "<td class=\"Kew_n9-bil_projek text-center sum\">{$row[0]}</td>";
			$sumRow .= "<td class=\"Kew_n9-peruntukan text-right sum\">{$row[1]}</td>";
			$sumRow .= '<td class="Kew_n9-belanja sum"></td>';
			$sumRow .= '<td class="Kew_n9-jimat sum"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: Kew_n9_header
	$headerCode = '';
	if(function_exists('Kew_n9_header')) {
		$args = [];
		$headerCode = Kew_n9_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Kew_n9_footer
	$footerCode = '';
	if(function_exists('Kew_n9_footer')) {
		$args = [];
		$footerCode = Kew_n9_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
