<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/Laporan.php");
	include_once("{$currDir}/Laporan_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('Laporan');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Laporan';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Laporan`.`id`" => "id",
		"`Laporan`.`program`" => "program",
		"FORMAT(`Laporan`.`peruntukan`, 2)" => "peruntukan",
		"`Laporan`.`bil_projek`" => "bil_projek",
		"`Laporan`.`bm`" => "bm",
		"`Laporan`.`Perolehan`" => "Perolehan",
		"`Laporan`.`dp`" => "dp",
		"`Laporan`.`sp`" => "sp",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Laporan`.`id`',
		2 => 2,
		3 => '`Laporan`.`peruntukan`',
		4 => '`Laporan`.`bil_projek`',
		5 => '`Laporan`.`bm`',
		6 => '`Laporan`.`Perolehan`',
		7 => '`Laporan`.`dp`',
		8 => '`Laporan`.`sp`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Laporan`.`id`" => "id",
		"`Laporan`.`program`" => "program",
		"FORMAT(`Laporan`.`peruntukan`, 2)" => "peruntukan",
		"`Laporan`.`bil_projek`" => "bil_projek",
		"`Laporan`.`bm`" => "bm",
		"`Laporan`.`Perolehan`" => "Perolehan",
		"`Laporan`.`dp`" => "dp",
		"`Laporan`.`sp`" => "sp",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Laporan`.`id`" => "ID",
		"`Laporan`.`program`" => "Program",
		"`Laporan`.`peruntukan`" => "Peruntukan Diluluskan",
		"`Laporan`.`bil_projek`" => "Bil Projek",
		"`Laporan`.`bm`" => "Belum Mula",
		"`Laporan`.`Perolehan`" => "Perolehan",
		"`Laporan`.`dp`" => "Dalam Perlaksanaan",
		"`Laporan`.`sp`" => "Siap Perlaksanaan",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Laporan`.`id`" => "id",
		"`Laporan`.`program`" => "program",
		"FORMAT(`Laporan`.`peruntukan`, 2)" => "peruntukan",
		"`Laporan`.`bil_projek`" => "bil_projek",
		"`Laporan`.`bm`" => "bm",
		"`Laporan`.`Perolehan`" => "Perolehan",
		"`Laporan`.`dp`" => "dp",
		"`Laporan`.`sp`" => "sp",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Laporan` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Laporan_view.php';
	$x->RedirectAfterInsert = 'Laporan_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Laporan Pemantauan';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Laporan`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Program', 'Peruntukan Diluluskan', 'Bil Projek', 'Belum Mula', 'Perolehan', 'Dalam Perlaksanaan', 'Siap Perlaksanaan', ];
	$x->ColFieldName = ['program', 'peruntukan', 'bil_projek', 'bm', 'Perolehan', 'dp', 'sp', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Laporan_templateTV.html';
	$x->SelectedTemplate = 'templates/Laporan_templateTVS.html';
	$x->TemplateDV = 'templates/Laporan_templateDV.html';
	$x->TemplateDVP = 'templates/Laporan_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Laporan_init
	$render = true;
	if(function_exists('Laporan_init')) {
		$args = [];
		$render = Laporan_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Laporan_header
	$headerCode = '';
	if(function_exists('Laporan_header')) {
		$args = [];
		$headerCode = Laporan_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Laporan_footer
	$footerCode = '';
	if(function_exists('Laporan_footer')) {
		$args = [];
		$footerCode = Laporan_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
