<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/pams_khas.php");
	include_once("{$currDir}/pams_khas_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('pams_khas');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'pams_khas';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`pams_khas`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "tahun_laksana",
		"IF(    CHAR_LENGTH(`waran1`.`sumber_waran`), CONCAT_WS('',   `waran1`.`sumber_waran`), '') /* Sumber Peruntukan */" => "Waran",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`pams_khas`.`NamaProjek`" => "NamaProjek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "AgensiPelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi pembayar */" => "agensi_pembayar",
		"`pams_khas`.`NamaKontraktor`" => "NamaKontraktor",
		"if(`pams_khas`.`TarikhSST`,date_format(`pams_khas`.`TarikhSST`,'%d/%m/%Y'),'')" => "TarikhSST",
		"if(`pams_khas`.`TarikhSiapProjek`,date_format(`pams_khas`.`TarikhSiapProjek`,'%d/%m/%Y'),'')" => "TarikhSiapProjek",
		"`pams_khas`.`TarikhSiapSepenuhnya`" => "TarikhSiapSepenuhnya",
		"IF(    CHAR_LENGTH(`skop_pams1`.`skop_pams`), CONCAT_WS('',   `skop_pams1`.`skop_pams`), '') /* Skop Kerja */" => "skop",
		"`pams_khas`.`gambar_projek`" => "gambar_projek",
		"`pams_khas`.`Latitud`" => "Latitud",
		"`pams_khas`.`Peta`" => "Peta",
		"FORMAT(`pams_khas`.`PeruntukanDiluluskan`, 2)" => "PeruntukanDiluluskan",
		"FORMAT(`pams_khas`.`peruntukan_dipinda`, 2)" => "peruntukan_dipinda",
		"FORMAT(`pams_khas`.`Kosprojek`, 2)" => "Kosprojek",
		"FORMAT(`pams_khas`.`KKSVO`, 2)" => "KKSVO",
		"`pams_khas`.`Perbelanjaan`" => "Perbelanjaan",
		"`pams_khas`.`Penjimatan`" => "Penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "penyelia_projek",
		"`pams_khas`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`pams_khas`.`sumber_permohonan`" => "sumber_permohonan",
		"`pams_khas`.`catatan`" => "catatan",
		"`pams_khas`.`inden`" => "inden",
		"`pams_khas`.`Baucer`" => "Baucer",
		"`pams_khas`.`gambar_projek_1`" => "gambar_projek_1",
		"`pams_khas`.`gambar_projek_2`" => "gambar_projek_2",
		"`pams_khas`.`updated`" => "updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`pams_khas`.`id`',
		2 => '`tahun1`.`tahun`',
		3 => '`waran1`.`sumber_waran`',
		4 => '`kelulusan1`.`kelulusan_jawatankuasa`',
		5 => 5,
		6 => '`negeri1`.`nama_negeri`',
		7 => '`daerah1`.`nama_daerah`',
		8 => '`PARLIMEN1`.`nama_parlimen`',
		9 => '`Dun1`.`nama_dun`',
		10 => '`agensi_pelaksana1`.`pelaksana`',
		11 => '`agensi_bayar1`.`agensi`',
		12 => 12,
		13 => '`pams_khas`.`TarikhSST`',
		14 => '`pams_khas`.`TarikhSiapProjek`',
		15 => 15,
		16 => '`skop_pams1`.`skop_pams`',
		17 => 17,
		18 => 18,
		19 => 19,
		20 => '`pams_khas`.`PeruntukanDiluluskan`',
		21 => '`pams_khas`.`peruntukan_dipinda`',
		22 => '`pams_khas`.`Kosprojek`',
		23 => '`pams_khas`.`KKSVO`',
		24 => '`pams_khas`.`Perbelanjaan`',
		25 => '`pams_khas`.`Penjimatan`',
		26 => '`status_pelaksanaan1`.`status_laksana`',
		27 => '`penyelia_projek1`.`nama_penyelia`',
		28 => 28,
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => 35,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`pams_khas`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "tahun_laksana",
		"IF(    CHAR_LENGTH(`waran1`.`sumber_waran`), CONCAT_WS('',   `waran1`.`sumber_waran`), '') /* Sumber Peruntukan */" => "Waran",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`pams_khas`.`NamaProjek`" => "NamaProjek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "AgensiPelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi pembayar */" => "agensi_pembayar",
		"`pams_khas`.`NamaKontraktor`" => "NamaKontraktor",
		"if(`pams_khas`.`TarikhSST`,date_format(`pams_khas`.`TarikhSST`,'%d/%m/%Y'),'')" => "TarikhSST",
		"if(`pams_khas`.`TarikhSiapProjek`,date_format(`pams_khas`.`TarikhSiapProjek`,'%d/%m/%Y'),'')" => "TarikhSiapProjek",
		"`pams_khas`.`TarikhSiapSepenuhnya`" => "TarikhSiapSepenuhnya",
		"IF(    CHAR_LENGTH(`skop_pams1`.`skop_pams`), CONCAT_WS('',   `skop_pams1`.`skop_pams`), '') /* Skop Kerja */" => "skop",
		"`pams_khas`.`gambar_projek`" => "gambar_projek",
		"`pams_khas`.`Latitud`" => "Latitud",
		"`pams_khas`.`Peta`" => "Peta",
		"FORMAT(`pams_khas`.`PeruntukanDiluluskan`, 2)" => "PeruntukanDiluluskan",
		"FORMAT(`pams_khas`.`peruntukan_dipinda`, 2)" => "peruntukan_dipinda",
		"FORMAT(`pams_khas`.`Kosprojek`, 2)" => "Kosprojek",
		"FORMAT(`pams_khas`.`KKSVO`, 2)" => "KKSVO",
		"`pams_khas`.`Perbelanjaan`" => "Perbelanjaan",
		"`pams_khas`.`Penjimatan`" => "Penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "penyelia_projek",
		"`pams_khas`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`pams_khas`.`sumber_permohonan`" => "sumber_permohonan",
		"`pams_khas`.`catatan`" => "catatan",
		"`pams_khas`.`inden`" => "inden",
		"`pams_khas`.`Baucer`" => "Baucer",
		"`pams_khas`.`gambar_projek_1`" => "gambar_projek_1",
		"`pams_khas`.`gambar_projek_2`" => "gambar_projek_2",
		"`pams_khas`.`updated`" => "updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`pams_khas`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "Tahun laksana",
		"IF(    CHAR_LENGTH(`waran1`.`sumber_waran`), CONCAT_WS('',   `waran1`.`sumber_waran`), '') /* Sumber Peruntukan */" => "Sumber Peruntukan",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`pams_khas`.`NamaProjek`" => "Nama Projek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "Negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "Agensi Pelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi pembayar */" => "Agensi pembayar",
		"`pams_khas`.`NamaKontraktor`" => "Nama Kontraktor",
		"`pams_khas`.`TarikhSST`" => "Tarikh SST",
		"`pams_khas`.`TarikhSiapProjek`" => "Tarikh Siap Projek",
		"`pams_khas`.`TarikhSiapSepenuhnya`" => "Tarikh Siap Sepenuhnya",
		"IF(    CHAR_LENGTH(`skop_pams1`.`skop_pams`), CONCAT_WS('',   `skop_pams1`.`skop_pams`), '') /* Skop Kerja */" => "Skop Kerja",
		"`pams_khas`.`Latitud`" => "Latitud",
		"`pams_khas`.`Peta`" => "Peta",
		"`pams_khas`.`PeruntukanDiluluskan`" => " Peruntukan Diluluskan",
		"`pams_khas`.`peruntukan_dipinda`" => "Peruntukan asal",
		"`pams_khas`.`Kosprojek`" => "Kos projek",
		"`pams_khas`.`KKSVO`" => "KKS / VO",
		"`pams_khas`.`Perbelanjaan`" => "Perbelanjaan",
		"`pams_khas`.`Penjimatan`" => "Penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "Penyelia projek",
		"`pams_khas`.`PenerimaManfaat`" => "Penerima Manfaat",
		"`pams_khas`.`sumber_permohonan`" => "Sumber Permohonan",
		"`pams_khas`.`catatan`" => "Catatan",
		"`pams_khas`.`inden`" => "Inden Kerja",
		"`pams_khas`.`Baucer`" => "Baucer Bayaran",
		"`pams_khas`.`updated`" => "Dikemaskini Oleh",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`pams_khas`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun laksana */" => "tahun_laksana",
		"IF(    CHAR_LENGTH(`waran1`.`sumber_waran`), CONCAT_WS('',   `waran1`.`sumber_waran`), '') /* Sumber Peruntukan */" => "Waran",
		"IF(    CHAR_LENGTH(`kelulusan1`.`kelulusan_jawatankuasa`), CONCAT_WS('',   `kelulusan1`.`kelulusan_jawatankuasa`), '') /* Kelulusan */" => "Kelulusan",
		"`pams_khas`.`NamaProjek`" => "NamaProjek",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* Negeri */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"IF(    CHAR_LENGTH(`agensi_pelaksana1`.`pelaksana`), CONCAT_WS('',   `agensi_pelaksana1`.`pelaksana`), '') /* Agensi Pelaksana */" => "AgensiPelaksana",
		"IF(    CHAR_LENGTH(`agensi_bayar1`.`agensi`), CONCAT_WS('',   `agensi_bayar1`.`agensi`), '') /* Agensi pembayar */" => "agensi_pembayar",
		"`pams_khas`.`NamaKontraktor`" => "NamaKontraktor",
		"if(`pams_khas`.`TarikhSST`,date_format(`pams_khas`.`TarikhSST`,'%d/%m/%Y'),'')" => "TarikhSST",
		"if(`pams_khas`.`TarikhSiapProjek`,date_format(`pams_khas`.`TarikhSiapProjek`,'%d/%m/%Y'),'')" => "TarikhSiapProjek",
		"`pams_khas`.`TarikhSiapSepenuhnya`" => "TarikhSiapSepenuhnya",
		"IF(    CHAR_LENGTH(`skop_pams1`.`skop_pams`), CONCAT_WS('',   `skop_pams1`.`skop_pams`), '') /* Skop Kerja */" => "skop",
		"`pams_khas`.`Latitud`" => "Latitud",
		"`pams_khas`.`Peta`" => "Peta",
		"FORMAT(`pams_khas`.`PeruntukanDiluluskan`, 2)" => "PeruntukanDiluluskan",
		"FORMAT(`pams_khas`.`peruntukan_dipinda`, 2)" => "peruntukan_dipinda",
		"FORMAT(`pams_khas`.`Kosprojek`, 2)" => "Kosprojek",
		"FORMAT(`pams_khas`.`KKSVO`, 2)" => "KKSVO",
		"`pams_khas`.`Perbelanjaan`" => "Perbelanjaan",
		"`pams_khas`.`Penjimatan`" => "Penjimatan",
		"IF(    CHAR_LENGTH(`status_pelaksanaan1`.`status_laksana`), CONCAT_WS('',   `status_pelaksanaan1`.`status_laksana`), '') /* Status */" => "Status",
		"IF(    CHAR_LENGTH(`penyelia_projek1`.`nama_penyelia`), CONCAT_WS('',   `penyelia_projek1`.`nama_penyelia`), '') /* Penyelia projek */" => "penyelia_projek",
		"`pams_khas`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`pams_khas`.`sumber_permohonan`" => "sumber_permohonan",
		"`pams_khas`.`catatan`" => "catatan",
		"`pams_khas`.`inden`" => "inden",
		"`pams_khas`.`Baucer`" => "Baucer",
		"`pams_khas`.`updated`" => "updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['tahun_laksana' => 'Tahun laksana', 'Waran' => 'Sumber Peruntukan', 'Kelulusan' => 'Kelulusan', 'negeri' => 'Negeri', 'Daerah' => 'Daerah', 'Parlimen' => 'Parlimen', 'DUN' => 'DUN', 'AgensiPelaksana' => 'Agensi Pelaksana', 'agensi_pembayar' => 'Agensi pembayar', 'skop' => 'Skop Kerja', 'Status' => 'Status', 'penyelia_projek' => 'Penyelia projek', ];

	$x->QueryFrom = "`pams_khas` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pams_khas`.`tahun_laksana` LEFT JOIN `waran` as waran1 ON `waran1`.`id`=`pams_khas`.`Waran` LEFT JOIN `kelulusan` as kelulusan1 ON `kelulusan1`.`id`=`pams_khas`.`Kelulusan` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pams_khas`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pams_khas`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pams_khas`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pams_khas`.`DUN` LEFT JOIN `agensi_pelaksana` as agensi_pelaksana1 ON `agensi_pelaksana1`.`id`=`pams_khas`.`AgensiPelaksana` LEFT JOIN `agensi_bayar` as agensi_bayar1 ON `agensi_bayar1`.`id`=`pams_khas`.`agensi_pembayar` LEFT JOIN `skop_pams` as skop_pams1 ON `skop_pams1`.`id`=`pams_khas`.`skop` LEFT JOIN `status_pelaksanaan` as status_pelaksanaan1 ON `status_pelaksanaan1`.`id`=`pams_khas`.`Status` LEFT JOIN `penyelia_projek` as penyelia_projek1 ON `penyelia_projek1`.`id`=`pams_khas`.`penyelia_projek` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 5;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'pams_khas_view.php';
	$x->RedirectAfterInsert = 'pams_khas_view.php?SelectedID=#ID#';
	$x->TableTitle = 'PAMS KHAS ';
	$x->TableIcon = 'resources/table_icons/house.png';
	$x->PrimaryKey = '`pams_khas`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tahun laksana', 'Sumber Peruntukan', 'Kelulusan', 'Nama Projek', 'Negeri', 'Daerah', 'Parlimen', 'DUN', 'Nama Kontraktor', 'Tarikh SST', 'Tarikh Siap Sepenuhnya', 'Skop Kerja', 'Gambar ', 'Peta', ' Peruntukan Diluluskan', 'Kos projek', 'KKS / VO', 'Perbelanjaan', 'Penjimatan', 'Status', 'Penyelia projek', 'Penerima Manfaat', 'Sumber Permohonan', 'Catatan', 'Gambar  ', 'Gambar projek', 'Dikemaskini Oleh', ];
	$x->ColFieldName = ['tahun_laksana', 'Waran', 'Kelulusan', 'NamaProjek', 'negeri', 'Daerah', 'Parlimen', 'DUN', 'NamaKontraktor', 'TarikhSST', 'TarikhSiapSepenuhnya', 'skop', 'gambar_projek', 'Peta', 'PeruntukanDiluluskan', 'Kosprojek', 'KKSVO', 'Perbelanjaan', 'Penjimatan', 'Status', 'penyelia_projek', 'PenerimaManfaat', 'sumber_permohonan', 'catatan', 'gambar_projek_1', 'gambar_projek_2', 'updated', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 15, 16, 17, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34, 35, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/pams_khas_templateTV.html';
	$x->SelectedTemplate = 'templates/pams_khas_templateTVS.html';
	$x->TemplateDV = 'templates/pams_khas_templateDV.html';
	$x->TemplateDVP = 'templates/pams_khas_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: pams_khas_init
	$render = true;
	if(function_exists('pams_khas_init')) {
		$args = [];
		$render = pams_khas_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: pams_khas_header
	$headerCode = '';
	if(function_exists('pams_khas_header')) {
		$args = [];
		$headerCode = pams_khas_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: pams_khas_footer
	$footerCode = '';
	if(function_exists('pams_khas_footer')) {
		$args = [];
		$footerCode = pams_khas_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
