<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/pemohon_pprt.php");
	include_once("{$currDir}/pemohon_pprt_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('pemohon_pprt');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'pemohon_pprt';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`pemohon_pprt`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun */" => "tahun",
		"`pemohon_pprt`.`gambar_projek`" => "gambar_projek",
		"`pemohon_pprt`.`gambar2`" => "gambar2",
		"`pemohon_pprt`.`gambar3`" => "gambar3",
		"`pemohon_pprt`.`Nama_pemohon`" => "Nama_pemohon",
		"`pemohon_pprt`.`sumber_mohon`" => "sumber_mohon",
		"`pemohon_pprt`.`status_tanah`" => "status_tanah",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* NEGERI */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"`pemohon_pprt`.`skop`" => "skop",
		"`pemohon_pprt`.`Latitud`" => "Latitud",
		"`pemohon_pprt`.`Longitud`" => "Longitud",
		"FORMAT(`pemohon_pprt`.`anggaran_kos`, 2)" => "anggaran_kos",
		"`pemohon_pprt`.`justifikasi`" => "justifikasi",
		"`pemohon_pprt`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`pemohon_pprt`.`nama_mpkk_jpkkp`" => "nama_mpkk_jpkkp",
		"`pemohon_pprt`.`no_tel_mpkk_jpkkp`" => "no_tel_mpkk_jpkkp",
		"`pemohon_pprt`.`catatan`" => "catatan",
		"`pemohon_pprt`.`status_permohonan`" => "status_permohonan",
		"`pemohon_pprt`.`status_kelulusan`" => "status_kelulusan",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`pemohon_pprt`.`ID`',
		2 => '`tahun1`.`tahun`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`negeri1`.`nama_negeri`',
		10 => '`daerah1`.`nama_daerah`',
		11 => '`PARLIMEN1`.`nama_parlimen`',
		12 => '`Dun1`.`nama_dun`',
		13 => 13,
		14 => 14,
		15 => 15,
		16 => '`pemohon_pprt`.`anggaran_kos`',
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => '`pemohon_pprt`.`status_kelulusan`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`pemohon_pprt`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun */" => "tahun",
		"`pemohon_pprt`.`gambar_projek`" => "gambar_projek",
		"`pemohon_pprt`.`gambar2`" => "gambar2",
		"`pemohon_pprt`.`gambar3`" => "gambar3",
		"`pemohon_pprt`.`Nama_pemohon`" => "Nama_pemohon",
		"`pemohon_pprt`.`sumber_mohon`" => "sumber_mohon",
		"`pemohon_pprt`.`status_tanah`" => "status_tanah",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* NEGERI */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"`pemohon_pprt`.`skop`" => "skop",
		"`pemohon_pprt`.`Latitud`" => "Latitud",
		"`pemohon_pprt`.`Longitud`" => "Longitud",
		"FORMAT(`pemohon_pprt`.`anggaran_kos`, 2)" => "anggaran_kos",
		"`pemohon_pprt`.`justifikasi`" => "justifikasi",
		"`pemohon_pprt`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`pemohon_pprt`.`nama_mpkk_jpkkp`" => "nama_mpkk_jpkkp",
		"`pemohon_pprt`.`no_tel_mpkk_jpkkp`" => "no_tel_mpkk_jpkkp",
		"`pemohon_pprt`.`catatan`" => "catatan",
		"`pemohon_pprt`.`status_permohonan`" => "status_permohonan",
		"`pemohon_pprt`.`status_kelulusan`" => "status_kelulusan",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`pemohon_pprt`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun */" => "Tahun",
		"`pemohon_pprt`.`Nama_pemohon`" => "Nama Pemohon",
		"`pemohon_pprt`.`sumber_mohon`" => "Sumber mohon",
		"`pemohon_pprt`.`status_tanah`" => "Status tanah",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* NEGERI */" => "NEGERI",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"`pemohon_pprt`.`skop`" => "Panjang Jalan (M)",
		"`pemohon_pprt`.`Latitud`" => "Latitud",
		"`pemohon_pprt`.`Longitud`" => "Peta",
		"`pemohon_pprt`.`anggaran_kos`" => "Kos projek",
		"`pemohon_pprt`.`justifikasi`" => "Justifikasi",
		"`pemohon_pprt`.`PenerimaManfaat`" => "Penerima Manfaat",
		"`pemohon_pprt`.`nama_mpkk_jpkkp`" => "Nama mpkk jpkkp",
		"`pemohon_pprt`.`no_tel_mpkk_jpkkp`" => "No tel mpkk jpkkp",
		"`pemohon_pprt`.`catatan`" => "Catatan",
		"`pemohon_pprt`.`status_permohonan`" => "Status permohonan",
		"`pemohon_pprt`.`status_kelulusan`" => "Status kelulusan",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`pemohon_pprt`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tahun1`.`tahun`), CONCAT_WS('',   `tahun1`.`tahun`), '') /* Tahun */" => "tahun",
		"`pemohon_pprt`.`Nama_pemohon`" => "Nama_pemohon",
		"`pemohon_pprt`.`sumber_mohon`" => "sumber_mohon",
		"`pemohon_pprt`.`status_tanah`" => "status_tanah",
		"IF(    CHAR_LENGTH(`negeri1`.`nama_negeri`), CONCAT_WS('',   `negeri1`.`nama_negeri`), '') /* NEGERI */" => "negeri",
		"IF(    CHAR_LENGTH(`daerah1`.`nama_daerah`), CONCAT_WS('',   `daerah1`.`nama_daerah`), '') /* Daerah */" => "Daerah",
		"IF(    CHAR_LENGTH(`PARLIMEN1`.`nama_parlimen`), CONCAT_WS('',   `PARLIMEN1`.`nama_parlimen`), '') /* Parlimen */" => "Parlimen",
		"IF(    CHAR_LENGTH(`Dun1`.`nama_dun`), CONCAT_WS('',   `Dun1`.`nama_dun`), '') /* DUN */" => "DUN",
		"`pemohon_pprt`.`skop`" => "skop",
		"`pemohon_pprt`.`Latitud`" => "Latitud",
		"`pemohon_pprt`.`Longitud`" => "Longitud",
		"FORMAT(`pemohon_pprt`.`anggaran_kos`, 2)" => "anggaran_kos",
		"`pemohon_pprt`.`justifikasi`" => "justifikasi",
		"`pemohon_pprt`.`PenerimaManfaat`" => "PenerimaManfaat",
		"`pemohon_pprt`.`nama_mpkk_jpkkp`" => "nama_mpkk_jpkkp",
		"`pemohon_pprt`.`no_tel_mpkk_jpkkp`" => "no_tel_mpkk_jpkkp",
		"`pemohon_pprt`.`catatan`" => "catatan",
		"`pemohon_pprt`.`status_permohonan`" => "status_permohonan",
		"`pemohon_pprt`.`status_kelulusan`" => "status_kelulusan",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['tahun' => 'Tahun', 'negeri' => 'NEGERI', 'Daerah' => 'Daerah', 'Parlimen' => 'Parlimen', 'DUN' => 'DUN', ];

	$x->QueryFrom = "`pemohon_pprt` LEFT JOIN `tahun` as tahun1 ON `tahun1`.`id`=`pemohon_pprt`.`tahun` LEFT JOIN `negeri` as negeri1 ON `negeri1`.`id`=`pemohon_pprt`.`negeri` LEFT JOIN `daerah` as daerah1 ON `daerah1`.`id`=`pemohon_pprt`.`Daerah` LEFT JOIN `PARLIMEN` as PARLIMEN1 ON `PARLIMEN1`.`id`=`pemohon_pprt`.`Parlimen` LEFT JOIN `Dun` as Dun1 ON `Dun1`.`id`=`pemohon_pprt`.`DUN` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'pemohon_pprt_view.php';
	$x->RedirectAfterInsert = 'pemohon_pprt_view.php?SelectedID=#ID#';
	$x->TableTitle = 'MOHON PPRT';
	$x->TableIcon = 'resources/table_icons/car_add.png';
	$x->PrimaryKey = '`pemohon_pprt`.`ID`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Tahun', 'Gambar projek', 'Gambar2', 'Gambar3', 'Nama Pemohon', 'Sumber mohon', 'Status tanah', 'NEGERI', 'Daerah', 'Parlimen', 'DUN', 'Panjang Jalan (M)', 'Latitud', 'Peta', 'Kos projek', 'Justifikasi', 'Penerima Manfaat', 'Nama mpkk jpkkp', 'No tel mpkk jpkkp', 'Catatan', 'Status permohonan', 'Status kelulusan', ];
	$x->ColFieldName = ['ID', 'tahun', 'gambar_projek', 'gambar2', 'gambar3', 'Nama_pemohon', 'sumber_mohon', 'status_tanah', 'negeri', 'Daerah', 'Parlimen', 'DUN', 'skop', 'Latitud', 'Longitud', 'anggaran_kos', 'justifikasi', 'PenerimaManfaat', 'nama_mpkk_jpkkp', 'no_tel_mpkk_jpkkp', 'catatan', 'status_permohonan', 'status_kelulusan', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/pemohon_pprt_templateTV.html';
	$x->SelectedTemplate = 'templates/pemohon_pprt_templateTVS.html';
	$x->TemplateDV = 'templates/pemohon_pprt_templateDV.html';
	$x->TemplateDVP = 'templates/pemohon_pprt_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: pemohon_pprt_init
	$render = true;
	if(function_exists('pemohon_pprt_init')) {
		$args = [];
		$render = pemohon_pprt_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])) {
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `pemohon_pprt`.`ID` in ('.substr($QueryWhere, 0, -1).')';
			} else { // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		} else {
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "SELECT FORMAT(SUM(`pemohon_pprt`.`anggaran_kos`), 2) FROM {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success sum">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<th class="text-center sum">&sum;</th>';
			$sumRow .= '<td class="pemohon_pprt-ID sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-tahun sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-gambar_projek sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-gambar2 sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-gambar3 sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-Nama_pemohon sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-sumber_mohon sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-status_tanah sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-negeri sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-Daerah sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-Parlimen sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-DUN sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-skop sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-Latitud sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-Longitud sum"></td>';
			$sumRow .= "<td class=\"pemohon_pprt-anggaran_kos text-left sum\">{$row[0]}</td>";
			$sumRow .= '<td class="pemohon_pprt-justifikasi sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-PenerimaManfaat sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-nama_mpkk_jpkkp sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-no_tel_mpkk_jpkkp sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-catatan sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-status_permohonan sum"></td>';
			$sumRow .= '<td class="pemohon_pprt-status_kelulusan sum"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: pemohon_pprt_header
	$headerCode = '';
	if(function_exists('pemohon_pprt_header')) {
		$args = [];
		$headerCode = pemohon_pprt_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: pemohon_pprt_footer
	$footerCode = '';
	if(function_exists('pemohon_pprt_footer')) {
		$args = [];
		$footerCode = pemohon_pprt_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
