<?php

// Data functions (insert, update, delete, form) for table status_kelulusan_pams

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function status_kelulusan_pams_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('status_kelulusan_pams');
	if(!$arrPerm['insert']) return false;

	$data = [
		'pemohon' => Request::lookup('pemohon', ''),
		'kelulusan' => Request::val('kelulusan', ''),
		'tarikh_kelulusan' => parseCode('<%%creationDateTime%%>', true, true),
		'pelulus' => parseCode('<%%creatorUsername%%>', true),
	];


	// hook: status_kelulusan_pams_before_insert
	if(function_exists('status_kelulusan_pams_before_insert')) {
		$args = [];
		if(!status_kelulusan_pams_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('status_kelulusan_pams', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('status_kelulusan_pams', $recID, calculated_fields()['status_kelulusan_pams']);

	// hook: status_kelulusan_pams_after_insert
	if(function_exists('status_kelulusan_pams_after_insert')) {
		$res = sql("SELECT * FROM `status_kelulusan_pams` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!status_kelulusan_pams_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('status_kelulusan_pams', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) status_kelulusan_pams_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function status_kelulusan_pams_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function status_kelulusan_pams_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('status_kelulusan_pams', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: status_kelulusan_pams_before_delete
	if(function_exists('status_kelulusan_pams_before_delete')) {
		$args = [];
		if(!status_kelulusan_pams_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `status_kelulusan_pams` WHERE `id`='{$selected_id}'", $eo);

	// hook: status_kelulusan_pams_after_delete
	if(function_exists('status_kelulusan_pams_after_delete')) {
		$args = [];
		status_kelulusan_pams_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='status_kelulusan_pams' AND `pkValue`='{$selected_id}'", $eo);
}

function status_kelulusan_pams_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('status_kelulusan_pams', $selected_id, 'edit')) return false;

	$data = [
		'pemohon' => Request::lookup('pemohon', ''),
		'kelulusan' => Request::val('kelulusan', ''),
	];

	// get existing values
	$old_data = getRecord('status_kelulusan_pams', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: status_kelulusan_pams_before_update
	if(function_exists('status_kelulusan_pams_before_update')) {
		$args = ['old_data' => $old_data];
		if(!status_kelulusan_pams_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'status_kelulusan_pams', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="status_kelulusan_pams_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('status_kelulusan_pams', $data['selectedID'], calculated_fields()['status_kelulusan_pams']);

	// hook: status_kelulusan_pams_after_update
	if(function_exists('status_kelulusan_pams_after_update')) {
		$res = sql("SELECT * FROM `status_kelulusan_pams` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!status_kelulusan_pams_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='status_kelulusan_pams' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function status_kelulusan_pams_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('status_kelulusan_pams');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_pemohon = thisOr($_REQUEST['filterer_pemohon'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: pemohon
	$combo_pemohon = new DataCombo;
	// combobox: kelulusan
	$combo_kelulusan = new Combo;
	$combo_kelulusan->ListType = 0;
	$combo_kelulusan->MultipleSeparator = ', ';
	$combo_kelulusan->ListBoxHeight = 10;
	$combo_kelulusan->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/status_kelulusan_pams.kelulusan.csv')) {
		$kelulusan_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/status_kelulusan_pams.kelulusan.csv')));
		$combo_kelulusan->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($kelulusan_data)));
		$combo_kelulusan->ListData = $combo_kelulusan->ListItem;
	} else {
		$combo_kelulusan->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("LULUS;;TIDAK LULUS;; KIV")));
		$combo_kelulusan->ListData = $combo_kelulusan->ListItem;
	}
	$combo_kelulusan->SelectName = 'kelulusan';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='status_kelulusan_pams' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='status_kelulusan_pams' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `status_kelulusan_pams` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'status_kelulusan_pams_view.php', false);
		}
		$combo_pemohon->SelectedData = $row['pemohon'];
		$combo_kelulusan->SelectedData = $row['kelulusan'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_pemohon->SelectedData = $filterer_pemohon;
		$combo_kelulusan->SelectedText = ( $_REQUEST['FilterField'][1] == '3' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
	}
	$combo_pemohon->HTML = '<span id="pemohon-container' . $rnd1 . '"></span><input type="hidden" name="pemohon" id="pemohon' . $rnd1 . '" value="' . html_attr($combo_pemohon->SelectedData) . '">';
	$combo_pemohon->MatchText = '<span id="pemohon-container-readonly' . $rnd1 . '"></span><input type="hidden" name="pemohon" id="pemohon' . $rnd1 . '" value="' . html_attr($combo_pemohon->SelectedData) . '">';
	$combo_kelulusan->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_pemohon__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['pemohon'] : htmlspecialchars($filterer_pemohon, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(pemohon_reload__RAND__) == 'function') pemohon_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function pemohon_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#pemohon-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_pemohon__RAND__.value, t: 'status_kelulusan_pams', f: 'pemohon' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="pemohon"]').val(resp.results[0].id);
							$j('[id=pemohon-container-readonly__RAND__]').html('<span id="pemohon-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=pams_mohon_view_parent]').hide(); } else { $j('.btn[id=pams_mohon_view_parent]').show(); }


							if(typeof(pemohon_update_autofills__RAND__) == 'function') pemohon_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'status_kelulusan_pams', f: 'pemohon' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_pemohon__RAND__.value = e.added.id;
				AppGini.current_pemohon__RAND__.text = e.added.text;
				$j('[name="pemohon"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=pams_mohon_view_parent]').hide(); } else { $j('.btn[id=pams_mohon_view_parent]').show(); }


				if(typeof(pemohon_update_autofills__RAND__) == 'function') pemohon_update_autofills__RAND__();
			});

			if(!$j("#pemohon-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_pemohon__RAND__.value, t: 'status_kelulusan_pams', f: 'pemohon' },
					success: function(resp) {
						$j('[name="pemohon"]').val(resp.results[0].id);
						$j('[id=pemohon-container-readonly__RAND__]').html('<span id="pemohon-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=pams_mohon_view_parent]').hide(); } else { $j('.btn[id=pams_mohon_view_parent]').show(); }

						if(typeof(pemohon_update_autofills__RAND__) == 'function') pemohon_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_pemohon__RAND__.value, t: 'status_kelulusan_pams', f: 'pemohon' },
				success: function(resp) {
					$j('[id=pemohon-container__RAND__], [id=pemohon-container-readonly__RAND__]').html('<span id="pemohon-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=pams_mohon_view_parent]').hide(); } else { $j('.btn[id=pams_mohon_view_parent]').show(); }

					if(typeof(pemohon_update_autofills__RAND__) == 'function') pemohon_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/status_kelulusan_pams_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/status_kelulusan_pams_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Status kelulusan permohonan details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return status_kelulusan_pams_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return status_kelulusan_pams_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return status_kelulusan_pams_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#pemohon').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#pemohon_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#kelulusan').replaceWith('<div class=\"form-control-static\" id=\"kelulusan\">' + (jQuery('#kelulusan').val() || '') + '</div>'); jQuery('#kelulusan-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(pemohon)%%>', $combo_pemohon->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(pemohon)%%>', $combo_pemohon->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(pemohon)%%>', urlencode($combo_pemohon->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(kelulusan)%%>', $combo_kelulusan->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(kelulusan)%%>', $combo_kelulusan->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('pemohon' => array('pams_mohon', 'Pemohon'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pemohon)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(kelulusan)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tarikh_kelulusan)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pelulus)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pemohon)%%>', safe_html($urow['pemohon']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pemohon)%%>', html_attr($row['pemohon']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pemohon)%%>', urlencode($urow['pemohon']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(kelulusan)%%>', safe_html($urow['kelulusan']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(kelulusan)%%>', html_attr($row['kelulusan']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(kelulusan)%%>', urlencode($urow['kelulusan']), $templateCode);
		$templateCode = str_replace('<%%VALUE(tarikh_kelulusan)%%>', app_datetime($row['tarikh_kelulusan'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tarikh_kelulusan)%%>', urlencode(app_datetime($urow['tarikh_kelulusan'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(pelulus)%%>', safe_html($urow['pelulus']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pelulus)%%>', urlencode($urow['pelulus']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pemohon)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pemohon)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(kelulusan)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(kelulusan)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tarikh_kelulusan)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tarikh_kelulusan)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(pelulus)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pelulus)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('status_kelulusan_pams');
	if($selected_id) {
		$jdata = get_joined_record('status_kelulusan_pams', $selected_id);
		if($jdata === false) $jdata = get_defaults('status_kelulusan_pams');
		$rdata = $row;
	}
	$templateCode .= loadView('status_kelulusan_pams-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: status_kelulusan_pams_dv
	if(function_exists('status_kelulusan_pams_dv')) {
		$args=[];
		status_kelulusan_pams_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}