<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/status_pelaksanaan.php");
	include_once("{$currDir}/status_pelaksanaan_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('status_pelaksanaan');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'status_pelaksanaan';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`status_pelaksanaan`.`id`" => "id",
		"`status_pelaksanaan`.`status_laksana`" => "status_laksana",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`status_pelaksanaan`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`status_pelaksanaan`.`id`" => "id",
		"`status_pelaksanaan`.`status_laksana`" => "status_laksana",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`status_pelaksanaan`.`id`" => "ID",
		"`status_pelaksanaan`.`status_laksana`" => "Status laksana",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`status_pelaksanaan`.`id`" => "id",
		"`status_pelaksanaan`.`status_laksana`" => "status_laksana",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`status_pelaksanaan` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'status_pelaksanaan_view.php';
	$x->RedirectAfterInsert = 'status_pelaksanaan_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Status pelaksanaan';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`status_pelaksanaan`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Status laksana', ];
	$x->ColFieldName = ['status_laksana', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/status_pelaksanaan_templateTV.html';
	$x->SelectedTemplate = 'templates/status_pelaksanaan_templateTVS.html';
	$x->TemplateDV = 'templates/status_pelaksanaan_templateDV.html';
	$x->TemplateDVP = 'templates/status_pelaksanaan_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: status_pelaksanaan_init
	$render = true;
	if(function_exists('status_pelaksanaan_init')) {
		$args = [];
		$render = status_pelaksanaan_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: status_pelaksanaan_header
	$headerCode = '';
	if(function_exists('status_pelaksanaan_header')) {
		$args = [];
		$headerCode = status_pelaksanaan_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: status_pelaksanaan_footer
	$footerCode = '';
	if(function_exists('status_pelaksanaan_footer')) {
		$args = [];
		$footerCode = status_pelaksanaan_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
