<?php

// Data functions (insert, update, delete, form) for table Syarikat_baru

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function Syarikat_baru_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Syarikat_baru');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Tahun_daftar' => Request::lookup('Tahun_daftar', ''),
		'negeri' => Request::lookup('negeri', ''),
		'daerah' => Request::val('daerah', ''),
		'nama_pemilik' => Request::val('nama_pemilik', ''),
		'nama_syarikat' => Request::val('nama_syarikat', ''),
		'Alamat' => br2nl(Request::val('Alamat', '')),
		'no_ssm' => Request::val('no_ssm', ''),
		'no_cidb' => Request::val('no_cidb', ''),
		'no_evendor' => Request::val('no_evendor', ''),
		'email' => Request::val('email', ''),
	];


	// hook: Syarikat_baru_before_insert
	if(function_exists('Syarikat_baru_before_insert')) {
		$args = [];
		if(!Syarikat_baru_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Syarikat_baru', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('Syarikat_baru', $recID, calculated_fields()['Syarikat_baru']);

	// hook: Syarikat_baru_after_insert
	if(function_exists('Syarikat_baru_after_insert')) {
		$res = sql("SELECT * FROM `Syarikat_baru` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!Syarikat_baru_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Syarikat_baru', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Syarikat_baru_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Syarikat_baru_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Syarikat_baru_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Syarikat_baru', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Syarikat_baru_before_delete
	if(function_exists('Syarikat_baru_before_delete')) {
		$args = [];
		if(!Syarikat_baru_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Syarikat_baru` WHERE `id`='{$selected_id}'", $eo);

	// hook: Syarikat_baru_after_delete
	if(function_exists('Syarikat_baru_after_delete')) {
		$args = [];
		Syarikat_baru_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Syarikat_baru' AND `pkValue`='{$selected_id}'", $eo);
}

function Syarikat_baru_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Syarikat_baru', $selected_id, 'edit')) return false;

	$data = [
		'Tahun_daftar' => Request::lookup('Tahun_daftar', ''),
		'negeri' => Request::lookup('negeri', ''),
		'daerah' => Request::val('daerah', ''),
		'nama_pemilik' => Request::val('nama_pemilik', ''),
		'nama_syarikat' => Request::val('nama_syarikat', ''),
		'Alamat' => br2nl(Request::val('Alamat', '')),
		'no_ssm' => Request::val('no_ssm', ''),
		'no_cidb' => Request::val('no_cidb', ''),
		'no_evendor' => Request::val('no_evendor', ''),
		'email' => Request::val('email', ''),
	];

	// get existing values
	$old_data = getRecord('Syarikat_baru', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Syarikat_baru_before_update
	if(function_exists('Syarikat_baru_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Syarikat_baru_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Syarikat_baru', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Syarikat_baru_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Syarikat_baru', $data['selectedID'], calculated_fields()['Syarikat_baru']);

	// hook: Syarikat_baru_after_update
	if(function_exists('Syarikat_baru_after_update')) {
		$res = sql("SELECT * FROM `Syarikat_baru` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Syarikat_baru_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Syarikat_baru' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Syarikat_baru_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Syarikat_baru');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_Tahun_daftar = thisOr($_REQUEST['filterer_Tahun_daftar'], '');
	$filterer_negeri = thisOr($_REQUEST['filterer_negeri'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Tahun_daftar
	$combo_Tahun_daftar = new DataCombo;
	// combobox: negeri
	$combo_negeri = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Syarikat_baru' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Syarikat_baru' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Syarikat_baru` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Syarikat_baru_view.php', false);
		}
		$combo_Tahun_daftar->SelectedData = $row['Tahun_daftar'];
		$combo_negeri->SelectedData = $row['negeri'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_Tahun_daftar->SelectedData = $filterer_Tahun_daftar;
		$combo_negeri->SelectedData = $filterer_negeri;
	}
	$combo_Tahun_daftar->HTML = '<span id="Tahun_daftar-container' . $rnd1 . '"></span><input type="hidden" name="Tahun_daftar" id="Tahun_daftar' . $rnd1 . '" value="' . html_attr($combo_Tahun_daftar->SelectedData) . '">';
	$combo_Tahun_daftar->MatchText = '<span id="Tahun_daftar-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Tahun_daftar" id="Tahun_daftar' . $rnd1 . '" value="' . html_attr($combo_Tahun_daftar->SelectedData) . '">';
	$combo_negeri->HTML = '<span id="negeri-container' . $rnd1 . '"></span><input type="hidden" name="negeri" id="negeri' . $rnd1 . '" value="' . html_attr($combo_negeri->SelectedData) . '">';
	$combo_negeri->MatchText = '<span id="negeri-container-readonly' . $rnd1 . '"></span><input type="hidden" name="negeri" id="negeri' . $rnd1 . '" value="' . html_attr($combo_negeri->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Tahun_daftar__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Tahun_daftar'] : htmlspecialchars($filterer_Tahun_daftar, ENT_QUOTES)); ?>"};
		AppGini.current_negeri__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['negeri'] : htmlspecialchars($filterer_negeri, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Tahun_daftar_reload__RAND__) == 'function') Tahun_daftar_reload__RAND__();
				if(typeof(negeri_reload__RAND__) == 'function') negeri_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Tahun_daftar_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Tahun_daftar-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Tahun_daftar__RAND__.value, t: 'Syarikat_baru', f: 'Tahun_daftar' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Tahun_daftar"]').val(resp.results[0].id);
							$j('[id=Tahun_daftar-container-readonly__RAND__]').html('<span id="Tahun_daftar-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tahun_view_parent]').hide(); } else { $j('.btn[id=tahun_view_parent]').show(); }


							if(typeof(Tahun_daftar_update_autofills__RAND__) == 'function') Tahun_daftar_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Syarikat_baru', f: 'Tahun_daftar' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Tahun_daftar__RAND__.value = e.added.id;
				AppGini.current_Tahun_daftar__RAND__.text = e.added.text;
				$j('[name="Tahun_daftar"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tahun_view_parent]').hide(); } else { $j('.btn[id=tahun_view_parent]').show(); }


				if(typeof(Tahun_daftar_update_autofills__RAND__) == 'function') Tahun_daftar_update_autofills__RAND__();
			});

			if(!$j("#Tahun_daftar-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Tahun_daftar__RAND__.value, t: 'Syarikat_baru', f: 'Tahun_daftar' },
					success: function(resp) {
						$j('[name="Tahun_daftar"]').val(resp.results[0].id);
						$j('[id=Tahun_daftar-container-readonly__RAND__]').html('<span id="Tahun_daftar-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tahun_view_parent]').hide(); } else { $j('.btn[id=tahun_view_parent]').show(); }

						if(typeof(Tahun_daftar_update_autofills__RAND__) == 'function') Tahun_daftar_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Tahun_daftar__RAND__.value, t: 'Syarikat_baru', f: 'Tahun_daftar' },
				success: function(resp) {
					$j('[id=Tahun_daftar-container__RAND__], [id=Tahun_daftar-container-readonly__RAND__]').html('<span id="Tahun_daftar-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tahun_view_parent]').hide(); } else { $j('.btn[id=tahun_view_parent]').show(); }

					if(typeof(Tahun_daftar_update_autofills__RAND__) == 'function') Tahun_daftar_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function negeri_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#negeri-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_negeri__RAND__.value, t: 'Syarikat_baru', f: 'negeri' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="negeri"]').val(resp.results[0].id);
							$j('[id=negeri-container-readonly__RAND__]').html('<span id="negeri-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=negeri_view_parent]').hide(); } else { $j('.btn[id=negeri_view_parent]').show(); }


							if(typeof(negeri_update_autofills__RAND__) == 'function') negeri_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Syarikat_baru', f: 'negeri' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_negeri__RAND__.value = e.added.id;
				AppGini.current_negeri__RAND__.text = e.added.text;
				$j('[name="negeri"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=negeri_view_parent]').hide(); } else { $j('.btn[id=negeri_view_parent]').show(); }


				if(typeof(negeri_update_autofills__RAND__) == 'function') negeri_update_autofills__RAND__();
			});

			if(!$j("#negeri-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_negeri__RAND__.value, t: 'Syarikat_baru', f: 'negeri' },
					success: function(resp) {
						$j('[name="negeri"]').val(resp.results[0].id);
						$j('[id=negeri-container-readonly__RAND__]').html('<span id="negeri-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=negeri_view_parent]').hide(); } else { $j('.btn[id=negeri_view_parent]').show(); }

						if(typeof(negeri_update_autofills__RAND__) == 'function') negeri_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_negeri__RAND__.value, t: 'Syarikat_baru', f: 'negeri' },
				success: function(resp) {
					$j('[id=negeri-container__RAND__], [id=negeri-container-readonly__RAND__]').html('<span id="negeri-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=negeri_view_parent]').hide(); } else { $j('.btn[id=negeri_view_parent]').show(); }

					if(typeof(negeri_update_autofills__RAND__) == 'function') negeri_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Syarikat_baru_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Syarikat_baru_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Syarikat details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Syarikat_baru_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Syarikat_baru_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Syarikat_baru_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Tahun_daftar').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Tahun_daftar_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#negeri').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#negeri_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#daerah').replaceWith('<div class=\"form-control-static\" id=\"daerah\">' + (jQuery('#daerah').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nama_pemilik').replaceWith('<div class=\"form-control-static\" id=\"nama_pemilik\">' + (jQuery('#nama_pemilik').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nama_syarikat').replaceWith('<div class=\"form-control-static\" id=\"nama_syarikat\">' + (jQuery('#nama_syarikat').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Alamat').replaceWith('<div class=\"form-control-static\" id=\"Alamat\">' + (jQuery('#Alamat').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#no_ssm').replaceWith('<div class=\"form-control-static\" id=\"no_ssm\">' + (jQuery('#no_ssm').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#no_cidb').replaceWith('<div class=\"form-control-static\" id=\"no_cidb\">' + (jQuery('#no_cidb').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#no_evendor').replaceWith('<div class=\"form-control-static\" id=\"no_evendor\">' + (jQuery('#no_evendor').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Tahun_daftar)%%>', $combo_Tahun_daftar->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Tahun_daftar)%%>', $combo_Tahun_daftar->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Tahun_daftar)%%>', urlencode($combo_Tahun_daftar->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(negeri)%%>', $combo_negeri->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(negeri)%%>', $combo_negeri->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(negeri)%%>', urlencode($combo_negeri->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('Tahun_daftar' => array('tahun', 'Tahun Daftar'), 'negeri' => array('negeri', 'Negeri'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Tahun_daftar)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(negeri)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(daerah)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nama_pemilik)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nama_syarikat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Alamat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(no_ssm)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(no_cidb)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(no_evendor)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Tahun_daftar)%%>', safe_html($urow['Tahun_daftar']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Tahun_daftar)%%>', html_attr($row['Tahun_daftar']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tahun_daftar)%%>', urlencode($urow['Tahun_daftar']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(negeri)%%>', safe_html($urow['negeri']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(negeri)%%>', html_attr($row['negeri']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(negeri)%%>', urlencode($urow['negeri']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(daerah)%%>', safe_html($urow['daerah']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(daerah)%%>', html_attr($row['daerah']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(daerah)%%>', urlencode($urow['daerah']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nama_pemilik)%%>', safe_html($urow['nama_pemilik']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nama_pemilik)%%>', html_attr($row['nama_pemilik']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama_pemilik)%%>', urlencode($urow['nama_pemilik']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nama_syarikat)%%>', safe_html($urow['nama_syarikat']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nama_syarikat)%%>', html_attr($row['nama_syarikat']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama_syarikat)%%>', urlencode($urow['nama_syarikat']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Alamat)%%>', safe_html($urow['Alamat']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(Alamat)%%>', safe_html($urow['Alamat'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Alamat)%%>', urlencode($urow['Alamat']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(no_ssm)%%>', safe_html($urow['no_ssm']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(no_ssm)%%>', html_attr($row['no_ssm']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(no_ssm)%%>', urlencode($urow['no_ssm']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(no_cidb)%%>', safe_html($urow['no_cidb']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(no_cidb)%%>', html_attr($row['no_cidb']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(no_cidb)%%>', urlencode($urow['no_cidb']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(no_evendor)%%>', safe_html($urow['no_evendor']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(no_evendor)%%>', html_attr($row['no_evendor']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(no_evendor)%%>', urlencode($urow['no_evendor']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Tahun_daftar)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tahun_daftar)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(negeri)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(negeri)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(daerah)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(daerah)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nama_pemilik)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama_pemilik)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nama_syarikat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama_syarikat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Alamat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Alamat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(no_ssm)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(no_ssm)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(no_cidb)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(no_cidb)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(no_evendor)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(no_evendor)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Syarikat_baru');
	if($selected_id) {
		$jdata = get_joined_record('Syarikat_baru', $selected_id);
		if($jdata === false) $jdata = get_defaults('Syarikat_baru');
		$rdata = $row;
	}
	$templateCode .= loadView('Syarikat_baru-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Syarikat_baru_dv
	if(function_exists('Syarikat_baru_dv')) {
		$args=[];
		Syarikat_baru_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}