<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/waran.php");
	include_once("{$currDir}/waran_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('waran');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'waran';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`waran`.`id`" => "id",
		"`waran`.`sumber_waran`" => "sumber_waran",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`waran`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`waran`.`id`" => "id",
		"`waran`.`sumber_waran`" => "sumber_waran",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`waran`.`id`" => "ID",
		"`waran`.`sumber_waran`" => "Sumber waran",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`waran`.`id`" => "id",
		"`waran`.`sumber_waran`" => "sumber_waran",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`waran` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'waran_view.php';
	$x->RedirectAfterInsert = 'waran_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Waran';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`waran`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Sumber waran', ];
	$x->ColFieldName = ['sumber_waran', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/waran_templateTV.html';
	$x->SelectedTemplate = 'templates/waran_templateTVS.html';
	$x->TemplateDV = 'templates/waran_templateDV.html';
	$x->TemplateDVP = 'templates/waran_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: waran_init
	$render = true;
	if(function_exists('waran_init')) {
		$args = [];
		$render = waran_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: waran_header
	$headerCode = '';
	if(function_exists('waran_header')) {
		$args = [];
		$headerCode = waran_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: waran_footer
	$footerCode = '';
	if(function_exists('waran_footer')) {
		$args = [];
		$footerCode = waran_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
